services:
  app:
    build: .
    volumes:
      - .:/var/www
    networks:
      - waste-net

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - waste-net

networks:
  waste-net:
    driver: bridge

volumes:
  mongo-data:
